forms/formGenerator/generateXForm.xsl
Was not picking up glosses with no xml:lang attribute. Fixed.
=> Fix issue with glosses

forms/formGenerator/generateXForm.xsl
Forms will need to be rerun to use this feature. The feature allows any element defined in the local schema to be inserted with all of the defined child elements.
=> Update xslt to allow forms to insert child elements #13

forms/formGenerator/generateXForm.xsl
Fixed bug generated by duplicate IDs in repeat elements.
@mMoliere This should fix the bug you discovered in the msContents.
=> Updates to fix bug here #50

forms/formGenerator/config.xml
@mMoliere I checked the file, one subform at a time. They all run except the decoDesc subform. I checked the schema and it is missing  an elementSpec for decoDesc, once you add that it should run fine. It is really important to have a complete schema for the forms to be built on. That is the first place to check if something goes wrong.
Let me know how it runs now.
=> Check config files

forms/formGenerator/generateXForm.xsl
Add collapsable menus to main page layout. #50
=> Updates to main page layout.

forms/schemas/mss-reproductions.xml
Update schema to correctly reference graphic as child of facsimile. This enables proper display of graphic element and its attributes.
=> Add reference to graphic element in the schema. #97

services/submit.xql
Also add in progress preview HTML function
=> Updates to fix some bugs in submit

forms/formGenerator/config.xml, forms/formGenerator/generateXForm.xsl
Example of title constructed by child elements. groupLabelConditionalElement, indicates which element must have content to trigger the display, if empty it defaults to the groupLabel, otherwise you have an empty label.
Also handles new label names.
Bumps version to 1.09.
=> Update group label display #117 #98

forms/formGenerator/generateXForm.xsl, resources/css/xforms.css
Adds a new change element with change/person/date. #145
=> updates for admin metadata. #145

forms/formGenerator/config.xml, forms/msSimple/ab.xhtml, forms/msSimple/templates/ab-elementTemplate.xml, forms/msSimple/templates/ab-schemaConstraints.xml, forms/schemas/full-mss-template.xml, forms/schemas/mss-definition.xml
Reverts majlis-erc/manuForma#177
=> Revert "tweaks to joins"

forms/formGenerator/generateXForm.xsl
@mMoliere This should fix the bug. Please test and let me know.
=> Update form generator to fix #179 bug

forms/formGenerator/generateXForm.xsl
@mMoliere please rerun the forms with this version. It should handle the issue.
=> Update xslt to fix #179

forms/formGenerator/config.xml, forms/msSimple/ab.xhtml
Reverts majlis-erc/manuForma#192
=> Revert "update joins"

forms/formGenerator/generateXForm.xsl
@mMoliere please try this version.
=> More updates for #179

forms/formGenerator/generateXForm.xsl
Updates attribute display within an element, using gloss.
=> Update attribute display. See #98

forms/formGenerator/generateXForm.xsl
@mMoliere  Please test v 1.21 for a fix for the extra text field in the bibliogrpahic element.
=> Update to remove extra text field in bibl element. #211

resources/js/app.js
This is another issue that should go back to the designers. The javascript is hiding buttons that are not empty.
=> Fix app.js that is incorrectly suppressing xforms buttons. #245

resources/css/style.css
Increase space between attributes and elements.
=> Update css for #271

forms/formGenerator/generateXForm.xsl
Updates to XSLT, will need to rerun, to update forms.
=> Update text in add buttons for repeatable groups. #270

forms/formGenerator/generateXForm.xsl
=> Update submit process, automate additions. #261

resources/css/style.css, resources/js/app.js
Patches for missing js and css in design updates, in particular this should hide the empty boxes in the element headers.
=> Update styles and javascript for new design.

controller.xql, login.html, modules/app.xql, modules/config.xqm, modules/userManager.xql, post-install.xql, repo.xml, resources/css/style.css, resources/js/login.js, templates/page.html, user.html
=> Updates for restricted access.

forms/formGenerator/generateXForm.xsl, services/git-commit.xql, services/submit.xql
@mMoliere please give this a try and see how it works for you. Note, you will need to re enter your $gitcommit:authorization-token, so make sure you have a saved copy somewhere, before you merge.
=> Update git-commit to open pull request on successful save. #251

forms/formGenerator/generateXForm.xsl
Small change to add description.
=> Add instructions to submit window. #389

forms/formGenerator/generateXForm.xsl
Add logic to deal with repeats in groups that contain child elements.
=> Update handling of subforms repeated groups #423

forms/formGenerator/generateXForm.xsl
Make sure scriptNote is inserted in the correct place to ensure validation.
=> Fix bug in #423

forms/formGenerator/test-persons-config.xml
@mMoliere Does this do what you want with the persons forms?
=> Test for subdividing persons form. #412

modules/app.xql
Fixes: https://github.com/majlis-erc/manuForma/issues/451
=> Remove account btn #451

forms/formGenerator/generateXForm.xsl
Does not work in all browsers. #22
Just going through and cleaning up remaining issues.
=> Hide download button

forms/formGenerator/config-persons-demo.xml, forms/schemas/person-schema.xml
@mMoliere I think this one should iron out all the issues. I ran it locally twice and it does run. Sorry for the back and forth!
=> Update for persons forms.

resources/css/xforms.css
Will respond based on type of text in text box.
@mMoliere This will require a hard refresh of your browser to take effect as it is a purely css fix. Let me know how it goes.
=> Update input/textarea to be bidirectional #476

forms/formGenerator/generateXForm.xsl
@mMoliere Tested on persons records. Please let me know how it works for you.
=> Update forms to select source from dropdown. #425

forms/formGenerator/generateXForm.xsl
This change also fixes the bug mentioned in #493
=> Correctly display idno #487

forms/formGenerator/config.xml, forms/msSimple/ab.xhtml, forms/msSimple/accMat.xhtml
Reverts majlis-erc/manuForma#501
=> Revert "added title to collapsible"

forms/formGenerator/config.xml, forms/msSimple/bindingDesc.xhtml, forms/msSimple/decoDesc.xhtml, forms/msSimple/handDesc.xhtml, forms/msSimple/history.xhtml, forms/msSimple/index.xhtml, forms/msSimple/layoutDesc.xhtml, forms/msSimple/msContents.xhtml, forms/msSimple/mssSupport.xhtml, forms/msSimple/templates/ab-schemaConstraints.xml, forms/msSimple/templates/accMat-schemaConstraints.xml, forms/msSimple/templates/additional-schemaConstraints.xml, forms/msSimple/templates/reproductions-schemaConstraints.xml, forms/templates/relations-template.xml
Reverts majlis-erc/manuForma#521
=> Revert "ptr bug"

forms/formGenerator/config.xml, forms/msSimple/ab.xhtml
Reverts majlis-erc/manuForma#524
=> Revert "comma fix"

services/get-rec.xql
Add a fail safe if not baseURI is included in config file.
=> Update to person ID search #535

forms/formGenerator/generateXForm.xsl
Fixes the lookups so they wrap the correct parent elements.
=> Fix bibliographic search #536

forms/formGenerator/config.xml, forms/msSimple/ab.xhtml, forms/msSimple/bindingDesc.xhtml, forms/msSimple/decoDesc.xhtml, forms/msSimple/handDesc.xhtml, forms/msSimple/history.xhtml, forms/msSimple/layoutDesc.xhtml, forms/msSimple/msContents.xhtml, forms/msSimple/msIdentifier.xhtml, forms/msSimple/mssSupport.xhtml, forms/msSimple/templates/msIdentifier-schemaConstraints.xml
Reverts majlis-erc/manuForma#579
=> Revert "dropdown fix"

controller.xql
Prevents guests access to forms. Fix bug for empty login.
=> Fix bug in login

forms/formGenerator/generateXForm.xsl
Suppress attribute was not working on nested lookups. Fixed. #569
=> Fix bug in extra lookups

services/get-rec.xql, services/submit.xql
This works only for summary, desc, note, quote and  p elements.
The only markdown accepted are paragraphs, line breaks and *em*
=> Updates for using markdown in textarea. #468

expath-pkg.xml
=> Trigger webhook

services/submit.xql
parse-xml function was stripping escape characters from ampersands. #634
=> Fix bug in submit.

forms/formGenerator/config-mss.xml, forms/formGenerator/generateXForm.xsl
Please test these changes. They should address broken lookups and correctly suppress unwanted lookups.
=> Updates for lookups #675

services/submit.xql
Try this fix: https://github.com/majlis-erc/manuForma/issues/639
=> Update for empty p elements

services/get-rec.xql
This should fix the extra pa elements
=> Update get record to correctly parse p elements #639

forms/formGenerator/generateXForm.xsl, services/submit.xql
Ensure correct editor is added.
=> Update to remove empty editor elements. #638

src/main/formGenerator/config-persons.xml
Code not run – needs to be integrated into rebuild.
=> modified collapsible

src/main/formGenerator/schemas/titleStmt.xml
Code not run – needs to be integrated into rebuild.
=> entry-editor role
